from abc import ABC, abstractmethod
from datetime import date
from typing import Any


class OneCClient(ABC):
    @abstractmethod
    def check_connection(self) -> dict: ...
    @abstractmethod
    def get_organizations(self) -> list[dict]: ...
    @abstractmethod
    def get_account_turnovers(self, organization_id: str, period_start: date, period_end: date, accounts: list[str]) -> list[dict]: ...
    @abstractmethod
    def get_account_balance(self, organization_id: str, period_start: date, period_end: date, account: str) -> dict: ...
    @abstractmethod
    def get_documents(self, organization_id: str, period_start: date, period_end: date, filters: dict[str, Any]) -> list[dict]: ...
    @abstractmethod
    def get_document_movements(self, document_ref: str) -> list[dict]: ...
    @abstractmethod
    def get_register_records(self, organization_id: str, period_start: date, period_end: date, register_name: str, filters: dict[str, Any]) -> list[dict]: ...
    @abstractmethod
    def get_accounting_policy(self, organization_id: str, period: date) -> dict: ...
    @abstractmethod
    def get_month_close_status(self, organization_id: str, period: date) -> dict: ...
    @abstractmethod
    def get_month_close_operations(self, organization_id: str, period: date) -> list[dict]: ...
    @abstractmethod
    def get_manual_operations(self, organization_id: str, period_start: date, period_end: date) -> list[dict]: ...
    @abstractmethod
    def get_vat_documents(self, organization_id: str, period_start: date, period_end: date) -> list[dict]: ...
    @abstractmethod
    def get_purchase_book_records(self, organization_id: str, period_start: date, period_end: date) -> list[dict]: ...
    @abstractmethod
    def get_sales_book_records(self, organization_id: str, period_start: date, period_end: date) -> list[dict]: ...
    @abstractmethod
    def get_fixed_assets(self, organization_id: str, period_start: date, period_end: date) -> list[dict]: ...
    @abstractmethod
    def get_depreciation_records(self, organization_id: str, period_start: date, period_end: date) -> list[dict]: ...
    @abstractmethod
    def get_advances(self, organization_id: str, period_start: date, period_end: date) -> list[dict]: ...
    @abstractmethod
    def get_counterparty_reconciliation_data(self, organization_id: str, period_start: date, period_end: date, counterparty_id: str) -> dict: ...
    @abstractmethod
    def get_inventory_balances(self, organization_id: str, period_start: date, period_end: date) -> list[dict]: ...
    @abstractmethod
    def get_inventory_movements(self, organization_id: str, period_start: date, period_end: date, filters: dict[str, Any]) -> list[dict]: ...
    @abstractmethod
    def get_payroll_summary(self, organization_id: str, period_start: date, period_end: date) -> dict: ...
    @abstractmethod
    def get_usn_income_expense_records(self, organization_id: str, period_start: date, period_end: date) -> list[dict]: ...
    @abstractmethod
    def get_reporting_indicators(self, organization_id: str, period_start: date, period_end: date, report_type: str) -> dict: ...
    @abstractmethod
    def get_user_permissions(self, user_identifier: str) -> dict: ...
    @abstractmethod
    def get_configuration_version(self) -> str: ...
    @abstractmethod
    def get_platform_version(self) -> str: ...
    @abstractmethod
    def get_extensions_info(self) -> list[dict]: ...
    @abstractmethod
    def get_last_update_info(self) -> dict: ...
